runtime! plugin/sensible.vim

set mouse=a

set spelllang=en_gb

syntax enable
set nowrap
set nojoinspaces

filetype plugin indent on

" character margin
set colorcolumn=80

" allow unsaved buffers in background
set hidden

" make splits appear on the right
set splitright

" Ctrl-P usage with fzf:
nmap <C-p> :Files<CR>

" using ag (if available) with ack.vim:
if executable('ag')
  set grepprg=ag\ --nogroup\ --nocolor
  let g:ackprg = 'ag --vimgrep'
endif

" vimwiki options
let g:vimwiki_list = [{
  \ 'path': '$HOME/.vimwiki',
  \ 'template_path': '$HOME/.vimwiki/templates',
  \ 'template_default': 'default',
  \ 'template_ext': '.html',
  \ }]

set background=dark
colorscheme elflord
