runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

runtime! plugin/sensible.vim

set mouse=a

syntax enable
set nowrap

filetype plugin indent on

" character margin
set colorcolumn=80

" allow unsaved buffers in background
set hidden

" make splits appear on the right
set splitright

" Ctrl-P usage with fzf:
nmap <C-p> :Files<CR>

" using ag (if available) with ack.vim:
if executable('ag')
  set grepprg=ag\ --nogroup\ --nocolor
  let g:ackprg = 'ag --vimgrep'
endif

" vimwiki options
let g:vimwiki_list = [{
  \ 'path': '$HOME/.vimwiki',
  \ 'template_path': '$HOME/.vimwiki/templates',
  \ 'template_default': 'default',
  \ 'template_ext': '.html',
  \ }]

" " with lightline.vim, I don't need the original modeline:
" set noshowmode

" " lightline.vim options:
" let g:lightline = {
"   \ 'colorscheme': 'powerline',
"   \ 'subseparator': { 'left': '', 'right': '' },
"   \ 'active': {
"   \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'filename' ] ],
"   \   'right': [ [], [], [ 'filetype' ] ],
"   \ },
"   \ 'inactive': {
"   \   'left': [ [ 'filename' ] ],
"   \   'right': [ [], [], [ 'filetype' ] ],
"   \ },
"   \ 'tabline': {
"   \   'left': [ [ 'tabs' ] ],
"   \   'right': [ [] ],
"   \ },
"   \ 'tab': {
"   \   'active': [ 'filename' ],
"   \   'inactive': [ 'filename' ],
"   \ },
"   \ 'component': {
"   \   'filetype': '%{&ft!=#"vim"?&ft:""}',
"   \ },
"   \ 'component_function': {
"   \   'filename': 'LightlineFilename',
"   \ },
"   \ 'tab_component_function': {
"   \   'filename': 'LightlineTabName',
"   \   'filetype': 'LightlineFiletype',
"   \ },
"   \ }

" function! LightlineCompose(name, modified)
"   let name = a:name !=# '' ? a:name : '[No Name]'
"   let modified = a:modified ? '•' : ''
"   return name . modified
" endfunction

" function! LightlineFilename()
"   return LightlineCompose(expand('%:t'), &modified)
" endfunction

" function! LightlineTabName(n)
"   let winnr = tabpagewinnr(a:n)
"   let buflist = tabpagebuflist(a:n)
"   let name = expand('#'.buflist[winnr - 1].':t')
"   let modified = gettabwinvar(a:n, winnr, '&modified')
"   return LightlineCompose(name, modified)
" endfunction

set background=dark
colorscheme elflord
